config:
  MD002: false # First heading should be a top-level heading
  MD013: false # Line length
  MD022: false # Headings should be surrounded by blank lines
  MD033: false # Inline HTML
  MD034: false # Bare URL used
  MD036: false # Emphasis used instead of a header
