title: Yoga cùng Linh Anh
email: yogacunglinhanh@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Yoga cho mẹ bầu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yogacunglinhanh.github.io"
twitter_username:
github_username: yogacunglinhanh

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  courses:
    output: true
  instructors:
    output: true
