title: Yoga cùng Linh Anh
email: yogacunglinhanh@gmail.com
description: >-
  Yoga cùng Linh Anh được sáng lập vào năm 2020 với mục tiêu giúp mọi người khoẻ
  "Tâm-Thân-Trí". Các bài tập/khoá học đều chú trọng rất nhiều về 3 mảng chính, động tác,
  hơi thở và reflection qua viết lách và thiền, để giúp mọi người tập Yoga 1 cách An Toàn
  - Hiệu Quả - Tràn Đầy Yêu Thương với cơ thể.
url: "yogacunglinhanh.github.io"
baseurl: ""
# search: true
instagram_username: ngoclinhdnl
facebook_username: groups/yoga.cung.linh.anh
youtube_username: yogacunglinhanh-noibanketn8829
tiktok_username: yogacunglinhanh
minimal_mistakes_skin: default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://www.instagram.com/ngoclinhdnl"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/groups/yoga.cung.linh.anh"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/@yogacunglinhanh-noibanketn8829"
    # - label: "TikTok"
    #   icon: "fab fa-fw fa-tiktok"
    #   url: "https://www.tiktok.com/@yogacunglinhanh"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
