name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup Bundler Cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('docs/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Update Bundle
        run: |
          bundle config set path vendor/bundle
          bundle install
          bundle clean

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Inject secrets
        run: |
          echo "google_script_url: ${{ secrets.GOOGLE_SCRIPT_URL }}" > _data/secrets.yml

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site/"

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'  # only deploy from main branch
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
